### ISSUE TITLE
URL do modelo acustico quebrada

### ISSUE THREAD

**Issue by racerxdl** [setecrs/julius-lapsam#1]
A URL do modelo acustico direciona para https://laps.ufpa.brfalabrasil/downloads.php porém mesmo corrigindo para https://laps.ufpa.br/falabrasil/downloads.php eu pego um 404.

Tem algum link alternativo?

**Comment by yuripourre** [comment]
Aqui tem alguns downloads, talvez seja esse o link que você procura: http://labvis.ufpa.br/falabrasil/downloads/

**Comment by racerxdl** [comment]
Ahh boa, é esse mesmo!
