### ISSUE TITLE
Como mudar sampling rate?

### ISSUE THREAD

**Issue by paulomaia20** [setecrs/julius-lapsam#3]
Olá,

Como é que posso alterar a sampling rate do ficheiro que quero transcrever? O default é de 16kHz mas o meu ficheiro tem 8kHz. Já tentei alterar o ficheiro julius.jconf.patch e o Dockerfile.

Obrigado

**Comment by atilaromero** [comment]
Desculpe pela demora em responder.
O CMD do container docker usa o seguinte commando para iniciar:
`sox - -r 16000 -e signed -b 16 -c 1 -t .wav - | julius -C julius.jconf -nolog -quiet #-progout `
A primeira parte converte o input recebido em stdin para 16kHz, então se você usar 
`cat my8hzfile.wav | docker run --rm -i setecrs/julius-lapsam`
ele deve (ou pelo menos deveria) converter de 8kHz para 16kHz sozinho.

Se você mudar os parâmetros do julius.jconf.patch para 8kHz, o comando sox vai atrapalhar, porque ele converte para 16kHz. Tem duas saídas fáceis: mudar o CMD para
`julius -C julius.jconf -nolog -quiet`
e aí ele não vai tentar converter primeiro, ou mudar o CMD para 
`sox - -r 8000 -e unsigned -b 8 -c 1 -t .wav - | julius -C julius.jconf -nolog -quiet `
Eu acho que a primeira opção é mais fácil.

**Comment by paulomaia20** [comment]
Muito obrigado!
