### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by pabloandrei** [setecrs/julius-lapsam#5]
Bom dia.

Alguém teria alguma documentação sobre o erro ocorrido.

```
STAT: include config: julius.jconf
Stat: para: parsing HTK Config file: edaz.conf
Warning: para: "USESILDET" ignored (not supported, or irrelevant)
Stat: para: ENORMALISE=T
Warning: para: NUMCEPS skipped (will be determined by AM header)
Stat: para: CEPLIFTER=22
Stat: para: NUMCHANS=26
Stat: para: PREEMCOEF=0.97
Stat: para: USEHAMMING=T
Stat: para: WINDOWSIZE=250000.0
Warning: para: "SAVEWITHCRC" ignored (not supported, or irrelevant)
Warning: para: "SAVECOMPRESSED" ignored (not supported, or irrelevant)
Stat: para: TARGETRATE=100000.0
Warning: para: TARGETKIND skipped (will be determined by AM header)
Stat: para: ZMEANSOURCE=T
Warning: para: "SOURCEFORMAT" ignored (not supported, or irrelevant)
Warning: no SOURCERATE found
Warning: assume source waveform sample rate to 625 (16kHz)

Segmentation fault (core dumped)
```

Efetuei um testes com um audio convertido de mp3 para wav de forma direta utilizando ffmpeg (ffmpeg -i input.mp3 output.wav).
O audio utilizado possui 60 minutos de duração.

Att.
Pablo

**Comment by atilaromero** [comment]
Não tinha visto esse erro antes.
Será que é a duração do áudio? Dá para tentar dividir ele em dois e testar
se ele processa as metades separadamente. Se processar, talvez seja muito
para ele.

**Comment by pabloandrei** [comment]
Boa tarde.

Fiz o split com do áudio e funcionou. Tenho várias duvidas sobre o tema, pelo entendimento a solução utiliza o Julius e etc.
Estou lendo este TCC: http://dsc.inf.furb.br/arquivos/tccs/monografias/2014_1_deivid-geovani-santana_monografia.pdf (Item 2.2)

Mas em geral gostaria de saber onde acho documentação sobre base "Language Model) para a linga portuguesa e etc.

![image](https://user-images.githubusercontent.com/16004192/110979406-52322e80-8343-11eb-894b-0e0d6e09e1b3.png)

Onde fica tais configurações:
![image](https://user-images.githubusercontent.com/16004192/110979530-7988fb80-8343-11eb-8d08-cf55da1c6760.png)

Ultima pergunta, já implementaram para microsservices com API?

**Comment by pabloandrei** [comment]
Achei os pontos elencados.

**Comment by atilaromero** [comment]
Na verdade eu nunca trabalhei a fundo com o Julius. O que aconteceu é que eu estava testando ele e achei que seria útil fazer os testes dentro de um container. Daí a criação deste projeto. Mais tarde o site onde o julius estava originalmente hospedado mudou e ficou bem difícil encontrar as bases necessárias. Daí eu incluir estes arquivos aqui no repositório, para facilitar para quem mais quisesse testar a solução deles. Por isso que estas questões mais técnicas do funcionamento do julius-lapsam eu não sei responder.
