### ISSUE TITLE
Arquivo "coruja_jlapsapi-1.7.+.zip" está corrompido

### ISSUE THREAD

**Issue by silvioprog** [setecrs/julius-lapsam#7]
Teria como reenviar o arquivo `coruja_jlapsapi-1.7.+.zip`? Tentei descompactá-lo no Windows e no Linux, porém diz que o arquivo está corrompido.

**Comment by atilaromero** [comment]
Eu acho que pode ter sido problema no download

**Comment by atilaromero** [comment]
Da para verificar pelo hash
sha256:c10c27dae22a83b51c99356719f4a0201cfc35a4908130e04e2f2671c9ea72bb

E pelo tamanho 191620889

**Comment by silvioprog** [comment]
Parece que é uma limitação do GitHub. Refiz o clone do repositório e o GitHub avisou que atingiu a [cota máxima permitida por repo](https://stackoverflow.com/questions/62905325/this-repository-is-over-its-data-quota-account-responsible-for-lfs-bandwidth-sh). 😕

Teria algum outro local para baixar este arquivo?

**Comment by atilaromero** [comment]
Sim! Vou fazer o seguinte: vou retirar o projeto do setecrs/julius-lapsam que e' mais usado e deixar so' no meu em atilaromero/julius-lapsam

**Comment by atilaromero** [comment]
"Bandwidth and storage usage only count against the repository owner's quotas. In forks, bandwidth and storage usage count against the root of the repository network. Anyone with write access to a repository can push files to Git LFS without affecting their personal bandwidth and storage quotas or purchasing data packs. Forking and pulling a repository counts against the parent repository's bandwidth limit."
Por isso que mover transferir o repositorio deve resolver

**Comment by silvioprog** [comment]
Show de bola!

**Comment by silvioprog** [comment]
Bah, ideia excelente! Só de curiosidade forkei no meu user e consegui baixar. Obrigado pelo ajuda @atilaromero, esse projeto é muito massa! 👏👏👏
